name: Build low-level API docs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  api-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HDF5_VERSION: 1.14.6
      HDF5_DIR: ${{ github.workspace }}/cache/hdf5
      TOXENV: apidocs
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Cache HDF5
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.HDF5_DIR }}
          key: ${{ runner.os }}-hdf5-${{ env.HDF5_VERSION }}

      - name: Build HDF5
        run: |
          ./ci/get_hdf5_if_needed.sh

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.12'

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python3 -m pip install tox

      - name: Build API docs
        run: |
          tox
          echo -n "api.h5py.org" > docs_api/_build/html/CNAME

      - name: Upload built docs
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: docs-html
          path: docs_api/_build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: github.repository == 'h5py/h5py' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs_api/_build/html
